# Generated by Django 5.2.1 on 2025-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expiration_date', models.DateField()),
                ('state', models.CharField(choices=[('PEND', 'Pending'), ('ACCE', 'Accepted'), ('REJ', 'Rejected'), ('CONT', 'Contingent')], default='PEND', max_length=4)),
                ('property_id', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
    ]
