# Generated by Django 5.2 on 2025-05-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('expiration_date', models.DateField()),
                ('state', models.TextField()),
                ('property_id', models.IntegerField()),
                ('seller', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
