# Generated by Django 5.2.1 on 2025-05-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('property', '0001_initial'),
        ('user_profile', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.sellerprofile'),
        ),
    ]
