# Generated by Django 5.2.1 on 2025-05-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offer_property_id_alter_offer_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
