# Generated by Django 5.2.1 on 2025-05-08 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_rename_property_id_offer_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
