# Generated by Django 5.2.1 on 2025-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contingent', 'Contingent')], default='pending', max_length=10),
        ),
    ]
