# Generated by Django 5.2.1 on 2025-05-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_offer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user',
            new_name='buyer',
        ),
    ]
