# Generated by Django 5.2.1 on 2025-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_rename_user_offer_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contingent_msg',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
