# Generated by Django 5.2.1 on 2025-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_rename_user_offer_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contingent_msg',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
