# Generated by Django 5.2.1 on 2025-05-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_offer_contingent_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
