# Generated by Django 5.2.1 on 2025-05-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_alter_offer_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contingent', 'Contingent'), ('finalized', 'Finalized')], default='pending', max_length=10),
        ),
    ]
