# Generated by Django 5.2.1 on 2025-05-14 10:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_alter_offer_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('house_nr', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('national_id', models.IntegerField(max_length=10)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='offer.offer')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
