# Generated by Django 5.2.1 on 2025-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_alter_offer_options_alter_offer_price_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='national_id',
            field=models.IntegerField(),
        ),
    ]
