# Generated by Django 5.2.1 on 2025-05-14 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0013_alter_transaction_national_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
