# Generated by Django 5.2.1 on 2025-05-14 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0014_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('house_nr', models.CharField(max_length=100)),
                ('city', models.CharField(default='Reykjavik', max_length=100)),
                ('country', models.CharField(default='Iceland')),
                ('postal_code', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('national_id', models.IntegerField()),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='offer.offer')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
