# Generated by Django 5.2.1 on 2025-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0015_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(),
        ),
    ]
