# Generated by Django 5.2.1 on 2025-05-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0016_alter_transaction_city_alter_transaction_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(max_length=200),
        ),
    ]
