# Generated by Django 5.2.1 on 2025-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0018_alter_transaction_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
