# Generated by Django 5.2.1 on 2025-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(default='images/default_profile_pic.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/default_profile_pic.png', upload_to='images/'),
        ),
    ]
