# Generated by Django 5.2.1 on 2025-05-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Real Estate Agency', 'Agency')], default='Individual'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
