# Generated by Django 5.2.1 on 2025-05-09 15:13

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_sellerprofile_type_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(upload_to=user_profile.models.profile_pic_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to=user_profile.models.profile_pic_path),
        ),
    ]
