# Generated by Django 5.2.1 on 2025-05-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_seller_alter_sellerprofile_logo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
