# Generated by Django 5.2.1 on 2025-05-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_delete_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='bio',
            field=models.TextField(max_length=600),
        ),
    ]
