# Generated by Django 5.2.1 on 2025-05-14 17:15

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='logo',
            field=models.ImageField(upload_to=user_profile.models.profile_pic_path),
        ),
    ]
