# Generated by Django 5.2.1 on 2025-05-15 14:46

import user_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_sellerprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='cover_img',
            field=models.ImageField(default=1, upload_to=user_profile.models.profile_pic_path),
            preserve_default=False,
        ),
    ]
