# Generated by Django 5.2.1 on 2025-05-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
