# Generated by Django 5.2.1 on 2025-05-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='static/images/no_image.jpg', upload_to='static/images/'),
        ),
    ]
