# Generated by Django 5.2.1 on 2025-05-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('AREA', 'Area')], default='AREA', max_length=9),
        ),
    ]
