# Generated by Django 5.2.1 on 2025-05-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='static/images/no_image.jpg', upload_to='media/'),
        ),
    ]
