# Generated by Django 5.2.1 on 2025-05-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_property_image'),
        ('user_profile', '0003_sellerprofile_logo_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user_profile.sellerprofile'),
            preserve_default=False,
        ),
    ]
