# Generated by Django 5.2.1 on 2025-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_property_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
