# Generated by Django 5.2.1 on 2025-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='property_images/'),
        ),
    ]
