# Generated by Django 5.2.1 on 2025-05-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_remove_property_image_propertyimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_preview',
            field=models.ImageField(default='images/no_image.jpg', upload_to='property_images/'),
        ),
    ]
