# Generated by Django 5.2.1 on 2025-05-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_property_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_preview',
        ),
        migrations.AddField(
            model_name='property',
            name='preview_pic',
            field=models.ImageField(default='property_images_no_image.jpg', upload_to='property_images/'),
        ),
    ]
