# Generated by Django 5.2.1 on 2025-05-09 09:39

import django.db.models.deletion
import property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_property_property_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='preview_pic',
            field=models.ImageField(upload_to=property.models.property_image_path),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to=property.models.property_images_path),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
    ]
