# Generated by Django 5.2.1 on 2025-05-09 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_property_preview_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
