# Generated by Django 5.2.1 on 2025-05-10 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_property_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Price must be positive')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800, message='Year built cannot be before 1800'), django.core.validators.MaxValueValidator(2025, message='Year built cannot be in the future')]),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='property.property'),
        ),
    ]
