# Generated by Django 5.2.1 on 2025-05-13 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_property_price_alter_property_year_built_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOUSE', 'House'), ('VILLA', 'Villa'), ('TOWNHOUSE', 'Townhouse'), ('AREA', 'Area')], default='AREA'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
