# Generated by Django 5.2.1 on 2025-05-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_propertyoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOffer',
        ),
    ]
